---
#make gathering facts to check OS version
- name: Gathering facts
  setup: 
  
- name: install nginx Debian
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

 
- name: install nginx Centos
  include_tasks: centos.yml
  when: ansible_os_family == "RedHat"

- name: copy defconfig
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify: reload nginx 
  tags: config